search_mode = "fuzzy"
filter_mode = "global"
workspaces = true

style = "full"
inline_height = 0
invert = true
show_preview = true
max_preview_height = 4
enter_accept = true

keymap_mode = "emacs"

show_help = true
show_tabs = true

secrets_filter = true

# Disable update check on every enter (managed via Homebrew)
update_check = false

[theme]
name = "catppuccin-mocha-mauve"

[stats]
common_subcommands = ["cargo", "docker", "git", "kubectl", "npm", "pnpm", "brew"]
common_prefix = ["sudo"]

[logs]
dir = "~/.local/state/atuin/logs"
